#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 RoaringBytes
"""scaffold_game.py — generates a new StratumV game project.

Creates the minimum viable game project structure with inline documentation.
The generated source files ARE the developer guide — every file explains the
engine contract it fulfills.

Output structure:
    {GameName}/
    ├── CMakeLists.txt              — build wiring (StratumV + plugins)
    ├── GAME_CONTRACT.md            — hard rules for plugin/game developers
    ├── DEVSERVER_API.md            — DevServer command reference
    └── src/
        ├── game/
        │   ├── SceneUBO.h          — GPU uniform buffer (std140)
        │   ├── GameSystemContext.h  — DLL boundary context extension
        │   ├── GameConfig.h        — config key constants
        │   ├── GameEngine.h        — EngineBase subclass (main engine class)
        │   └── GameEngine.cpp      — Engine init, shutdown, main loop + entry point
        └── plugins/
            └── example_plugin/
                ├── CMakeLists.txt
                ├── ExamplePlugin.h
                └── ExamplePlugin.cpp

Usage:
    python tools/scaffold_game.py MyGame
    python tools/scaffold_game.py MyGame --output /path/to/output
    python tools/scaffold_game.py MyGame --force   # overwrite existing
"""

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


# ═══════════════════════════════════════════════════════════════════════
#  Templates — $GAME$ is replaced with the game name
# ═══════════════════════════════════════════════════════════════════════

# ─── SceneUBO.h ───────────────────────────────────────────────────────

TPL_SCENE_UBO = """\
#pragma once
// ============================================================
// SceneUBO.h — Per-frame GPU uniform buffer (std140 layout)
// ============================================================
//
// This struct is uploaded to the GPU every frame as a uniform buffer
// object (UBO). It carries all per-frame scene state that your
// shaders need: camera matrices, lighting, time, etc.
//
// ── std140 Alignment Rules ────────────────────────────────────
//
// GLSL's std140 layout imposes strict alignment requirements.
// Your C++ struct MUST match your GLSL declaration byte-for-byte.
//
//   C++ Type        GLSL Type    Alignment   Size
//   ──────────────  ──────────   ─────────   ────
//   float           float        4           4
//   int32_t         int          4           4
//   uint32_t        uint         4           4
//   glm::vec2       vec2         8           8
//   glm::vec3       vec3         16          12  *** aligned to 16!
//   glm::vec4       vec4         16          16
//   glm::mat4       mat4         16          64  (4 x vec4 columns)
//   T[N] array      T[N]         16          N x roundUp(sizeof(T), 16)
//
// Common mistakes:
//   1. Using vec3 — it aligns to 16 bytes but only occupies 12,
//      creating a 4-byte gap. Use vec4 instead and pack data in .w.
//   2. Forgetting that array elements are each rounded to 16 bytes.
//      float[4] in std140 is 64 bytes (4 x 16), not 16.
//   3. Not adding explicit padding when scalar groups don't fill
//      a full vec4 slot.
//
// ── GLSL Declaration ──────────────────────────────────────────
//
// Mirror this struct EXACTLY in your shader:
//
//   layout(std140, set = 0, binding = 0) uniform SceneBlock {
//       mat4  viewProj;
//       mat4  invViewProj;
//       mat4  prevViewProj;
//       vec4  cameraPos;
//       vec4  sunDirection;
//       vec4  sunColor;
//       vec4  ambientColor;
//       float time;
//       float deltaTime;
//       uint  frameIndex;
//       float _pad0;
//       float jitterX;
//       float jitterY;
//       uint  renderWidth;
//       uint  renderHeight;
//       mat4  lightViewProj[3];
//   } scene;
//
// ── Ownership ─────────────────────────────────────────────────
//
// This struct is 100% game-defined. The engine does not read it.
// Your game code fills it each frame and uploads it to the GPU.
// Engine render passes (shadow, post-process) use their own UBOs.
//
// Generated by scaffold_game.py for $GAME$

#include <glm/glm.hpp>
#include <cstdint>

namespace sv {

struct SceneUBO {

    // ── Matrices (offsets 0-191, 192 bytes) ───────────────────
    //
    // viewProj:     current frame's view x projection matrix.
    // invViewProj:  inverse — for reconstructing world pos from depth.
    // prevViewProj: previous frame's VP — for temporal reprojection (TAA/DLSS).

    glm::mat4 viewProj     = glm::mat4(1.0f);  // offset   0
    glm::mat4 invViewProj  = glm::mat4(1.0f);  // offset  64
    glm::mat4 prevViewProj = glm::mat4(1.0f);  // offset 128

    // ── Camera (offset 192, 16 bytes) ─────────────────────────
    //
    // xyz = world-space camera position. w is free — use for a game
    // value (e.g. camera altitude) or leave as 0.

    glm::vec4 cameraPos = glm::vec4(0.0f);     // offset 192

    // ── Lighting (offsets 208-255, 48 bytes) ──────────────────

    glm::vec4 sunDirection = glm::vec4(0.0f, -1.0f, 0.0f, 0.0f);  // offset 208, xyz = dir TO sun
    glm::vec4 sunColor     = glm::vec4(1.0f, 1.0f, 1.0f, 1.0f);   // offset 224, a = intensity
    glm::vec4 ambientColor = glm::vec4(0.1f, 0.1f, 0.12f, 1.0f);  // offset 240, a = intensity

    // ── Time / Frame (offset 256, 16 bytes) ───────────────────
    //
    // Four scalars packed into one vec4-sized slot.
    // _pad0 keeps alignment; use it for a game value or leave zero.

    float    time       = 0.0f;   // offset 256, seconds since engine start
    float    deltaTime  = 0.0f;   // offset 260, seconds since last frame
    uint32_t frameIndex = 0;      // offset 264, monotonic frame counter
    float    _pad0      = 0.0f;   // offset 268, alignment padding

    // ── DLSS / TAA Jitter (offset 272, 16 bytes) ──────────────
    //
    // When DLSS is active, the engine applies sub-pixel jitter.
    // Upload these values so shaders can compensate in motion vectors.

    float    jitterX      = 0.0f;  // offset 272
    float    jitterY      = 0.0f;  // offset 276
    uint32_t renderWidth  = 0;     // offset 280, internal render res (may differ from window)
    uint32_t renderHeight = 0;     // offset 284

    // ── Shadow Cascades (offset 288, 192 bytes) ───────────────
    //
    // StratumV ShadowPass supports 3 cascaded shadow maps.
    // The engine fills these matrices each frame if shadows are active.
    // In your shader: lightViewProj[cascadeIndex] transforms
    // world-space position to light clip space.

    glm::mat4 lightViewProj[3] = {
        glm::mat4(1.0f), glm::mat4(1.0f), glm::mat4(1.0f)
    };  // offset 288, 3 x 64 = 192 bytes

    // ── Game-Specific Fields ──────────────────────────────────
    //
    // Add your fields below. Examples:
    //
    //   // Fog (4 floats = 1 vec4 slot, no padding needed)
    //   float fogDensity  = 0.01f;   // offset 480
    //   float fogStart    = 50.0f;   // offset 484
    //   float fogEnd      = 500.0f;  // offset 488
    //   float fogHeight   = 100.0f;  // offset 492
    //
    //   // Wind (vec4 = naturally aligned)
    //   glm::vec4 wind = glm::vec4(1, 0, 0, 5.0f); // xyz=dir, w=speed
    //
    // After adding fields:
    //   1. Update the static_assert below with the new size.
    //   2. Mirror the fields in your GLSL SceneBlock declaration.
    //   3. Keep the total size a multiple of 16 bytes.
};

// If this fires, your struct and GLSL are out of sync. Fix before shipping.
static_assert(sizeof(SceneUBO) == 480,
    "SceneUBO size mismatch — check std140 alignment and padding");

/// Fill sensible lighting defaults for a new scene.
inline void fillSceneDefaults(SceneUBO& ubo) {
    ubo.sunDirection = glm::vec4(0.3f, -0.8f, 0.5f, 0.0f);
    ubo.sunColor     = glm::vec4(1.0f, 0.95f, 0.9f, 1.0f);
    ubo.ambientColor = glm::vec4(0.08f, 0.09f, 0.12f, 1.0f);
}

} // namespace sv
"""

# ─── GameSystemContext.h ──────────────────────────────────────────────

TPL_GAME_SYSTEM_CONTEXT = """\
#pragma once
// ============================================================
// GameSystemContext.h — DLL boundary context for $GAME$
// ============================================================
//
// ── Why This File Exists ──────────────────────────────────────
//
// Every DLL plugin receives a SystemContext reference in init(),
// tick(), and record*() calls. SystemContext is forward-declared
// in IModularSystem.h (in namespace sv) — YOUR game defines it.
//
// SystemContext extends BaseSystemContext (~155 leaf fields), which
// is organised as a flat hot core plus eleven nested POD sub-structs
// (StratumV 1.3.0). Access paths:
//
//   Flat (hot, always present):
//     ctx.device, ctx.allocator, ctx.ecs, ctx.events
//     ctx.windowWidth / windowHeight / isBorderlessFullscreen
//     ctx.wireframeEnabled / gamePaused / requestShutdown / adminOpen
//     ctx.engineLog, ctx.physics
//
//   NOTE: ctx.network is a sub-struct in 1.3.0, not a flat pointer.
//   Write ctx.network.context->tick() — NOT ctx.network->tick().
//   The migration from 1.2.x is mechanical; see CHANGELOG.md §1.3.0.
//
//   ctx.rendering — RenderingContext (29 fields)
//     formats, resolution, frame index, scene desc layouts,
//     GPU feature flags, quality settings, postProcMutable,
//     getGraphicsPipeline, register/unregisterRenderPass,
//     HZB (imageView/sampler/width/height/mips), captureScreenshot
//
//   ctx.ui — UIContext (12 fields)
//     imguiContext, adminDecoRects, UI style JSON blobs,
//     uiBg/Glass/AtmoPipeLayout, saveStyleSection, uiShadersEnabled
//
//   ctx.input — InputContext (15 fields)
//     isKeyPressed/isKeyDown, getMousePos, isMouseDown,
//     getScrollDelta, cursor lock, toggleFullscreen,
//     action queries (isActionDown/Pressed/getActionAxis),
//     gamepad (connected/button/axis)
//
//   ctx.buffers — BufferContext (7 fields)
//     createBuffer, destroyBuffer, mapBuffer, unmapBuffer,
//     createShaderModule, createImage, destroyImage
//
//   ctx.vkfn — VulkanFnContext (29 PFN_vk*)
//     fnCmdBindPipeline, fnCmdDrawIndexed, fnCmdDispatch,
//     fnCreate/Destroy DescriptorPool/Layout/PipelineLayout,
//     fnCreate/Destroy Sampler/ImageView/Pipeline/ShaderModule …
//
//   ctx.meshRegistry — MeshRegistryContext (9 fields)
//     registerMesh, registerMaterial, getMeshSlot,
//     meshSlotSSBO, materialSSBO, megaVBO, megaIBO,
//     registeredMeshCount, registeredMaterialCount
//
//   ctx.audio — AudioContext (8 fields)
//     postAudioEvent, postAudioEventAt, stopAudioEvent,
//     stopAudioByTag, setAudioParam, setAudioEnvironment,
//     setAudioVolume, getAudioVolume
//
//   ctx.animation — AnimationContext (10 fields)
//     animationSystem, bonePaletteSSBO/Layout/DescSet,
//     resetBonePalette, uploadBones, flushBonePalette,
//     skinnedMeshPass, skinnedPipeLayout, skinnedShadowPipeLayout
//
//   ctx.world — WorldContext (2 fields)
//     worldBounds (from config world.boundsMin/Max),
//     assetManifest (engine-owned preload list)
//
//   ctx.perf — PerformanceContext
//     budget + frame/draw/VRAM counters + perf.network.* (passive
//     runtime observability: bytesPerSec, tickMs, packetsPerSec,
//     replicatedEntityCount, ackLatencyMs, droppedDatagramPct)
//
//   ctx.network — NetworkContext (1.3.0)
//     context — INetworkContext* (client-side interface; null if
//               networking is not wired; create via
//               createNoOpNetworkContext() or a concrete impl).
//     NOTE: ctx.network is a compound value, not a pointer. Access
//     the interface via ctx.network.context->... — writing
//     ctx.network->... will not compile after the 1.3.0 bump.
//
// Migration from pre-1.2.0 flat layout:
//   ctx.isKeyDown(K)            →  ctx.input.isKeyDown(K)
//   ctx.createBuffer(...)       →  ctx.buffers.createBuffer(...)
//   ctx.fnCmdBindPipeline       →  ctx.vkfn.fnCmdBindPipeline
//   ctx.postAudioEvent("snd")   →  ctx.audio.postAudioEvent("snd")
//   ctx.hzbImageView            →  ctx.rendering.hzbImageView
//   ctx.animationSystem         →  ctx.animation.animationSystem
//   ctx.worldBounds             →  ctx.world.worldBounds
//
// Migration from 1.2.x → 1.3.0:
//   ctx.network->tick()         →  ctx.network.context->tick()
//   if (ctx.network) { ... }    →  if (ctx.network.context) { ... }
//   ctx.network = impl.get()    →  ctx.network.context = impl.get()
//
// See BaseSystemContext.h or docs/ENGINE_REF.md for the full API.
//
// ── What You Add Here ─────────────────────────────────────────
//
// Game-specific state that plugins need:
//   - Pointers to game UBOs (SceneUBO, TerrainUBO, etc.)
//   - Function pointers for cross-plugin services (set in postInit)
//   - Game-specific shared state (world clock, weather, biome, etc.)
//
// ── CRITICAL: Namespace Rule ──────────────────────────────────
//
// SystemContext MUST be defined in namespace sv, because that's
// where IModularSystem.h forward-declares it:
//
//   namespace sv { struct SystemContext; }
//
// If you define it in a different namespace, IModularSystem's
// init(const SystemContext&) won't resolve to your definition.
//
// Generated by scaffold_game.py for $GAME$

#include "BaseSystemContext.h"
#include "SceneUBO.h"

namespace sv {

struct SystemContext : BaseSystemContext {

    // ── Game UBO Access ───────────────────────────────────────
    //
    // Most plugins only need read access to the scene UBO.
    // Systems that update scene state (sky, time-of-day) get
    // mutable access. Set both in your game's main loop.

    const SceneUBO* sceneState        = nullptr;  // read-only
    SceneUBO*       sceneStateMutable = nullptr;  // for scene-updating systems

    // ── Game-Specific Extensions ──────────────────────────────
    //
    // Add your game's shared state below. Guidelines:
    //
    //   1. Use POINTERS, not values. SystemContext is passed by
    //      reference across DLL boundaries — large values bloat it.
    //
    //   2. For cross-plugin services, use std::function<> pointers.
    //      Set them in postInit() of the providing system.
    //      Example:
    //
    //        // In SystemContext:
    //        std::function<float(float x, float z)> getTerrainHeight;
    //
    //        // In TerrainSystem::postInit():
    //        ctx.getTerrainHeight = [this](float x, float z) {
    //            return m_heightmap.sample(x, z);
    //        };
    //
    //        // In any other plugin's tick():
    //        if (ctx.getTerrainHeight) {
    //            float h = ctx.getTerrainHeight(pos.x, pos.z);
    //        }
    //
    //   3. Always null-check function pointers before calling.
    //      The providing system may not be loaded, or may have
    //      a higher initPriority (loads later).
    //
    //   4. Don't pass STL containers across DLL boundaries.
    //      Use C-compatible types: const char*, raw pointers,
    //      std::function<>, plain structs.

    // TODO: Add your game-specific fields here.
    // Examples:
    //   const TerrainUBO* terrainState = nullptr;
    //   std::function<float(float x, float z)> getTerrainHeight;
    //   float* oceanWaterLevel = nullptr;
    //   bool*  isUnderwater    = nullptr;
};

} // namespace sv
"""

# ─── GameConfig.h ─────────────────────────────────────────────────────

TPL_GAME_CONFIG = """\
#pragma once
// ============================================================
// GameConfig.h — Config key constants and defaults for $GAME$
// ============================================================
//
// StratumV's Config system uses a JSON file (config.json) with
// dot-path accessors:
//
//   sv::Config config;
//   config.loadFromFile("config.json");
//   int w = config.get<int>("window.width", 1920);
//   config.set("audio.master_volume", 0.8f);
//   config.saveToFile("config.json");
//
// This file centralizes key strings and default values to
// prevent typos and make it easy to see what's configurable.
//
// JSON structure example (config.json):
//   {
//     "window": {
//       "width": 1920,
//       "height": 1080,
//       "fullscreen": false,
//       "title": "$GAME$"
//     },
//     "render": {
//       "dlss_enabled": true,
//       "dlss_quality": 1
//     },
//     "audio": {
//       "master_volume": 1.0
//     }
//   }
//
// Generated by scaffold_game.py for $GAME$

#include <cstdint>

namespace $GAME$ {
namespace cfg {

    // ── Window ────────────────────────────────────────────────
    constexpr const char* kWindowWidth      = "window.width";
    constexpr const char* kWindowHeight     = "window.height";
    constexpr const char* kWindowFullscreen = "window.fullscreen";
    constexpr const char* kWindowTitle      = "window.title";

    constexpr int  kDefaultWindowWidth      = 1920;
    constexpr int  kDefaultWindowHeight     = 1080;
    constexpr bool kDefaultWindowFullscreen = false;

    // ── Render ────────────────────────────────────────────────
    constexpr const char* kRenderDlssEnabled = "render.dlss_enabled";
    constexpr const char* kRenderDlssQuality = "render.dlss_quality";
    constexpr const char* kRenderFpsCap      = "render.fps_cap";

    constexpr bool kDefaultDlssEnabled  = true;
    constexpr int  kDefaultDlssQuality  = 1;   // 0=Perf 1=Balanced 2=Quality 3=Ultra
    constexpr int  kDefaultFpsCap       = 0;   // 0 = uncapped

    // ── Audio ─────────────────────────────────────────────────
    constexpr const char* kAudioMasterVolume = "audio.master_volume";
    constexpr const char* kAudioSfxVolume    = "audio.sfx_volume";
    constexpr const char* kAudioMusicVolume  = "audio.music_volume";

    constexpr float kDefaultMasterVolume = 1.0f;
    constexpr float kDefaultSfxVolume    = 1.0f;
    constexpr float kDefaultMusicVolume  = 0.7f;

    // ── Game-Specific ─────────────────────────────────────────
    //
    // TODO: Add your game's config keys here.
    // Examples:
    //   constexpr const char* kGameDifficulty = "game.difficulty";
    //   constexpr const char* kGameFovDeg     = "game.fov_degrees";
    //   constexpr int   kDefaultDifficulty = 1;
    //   constexpr float kDefaultFovDeg     = 90.0f;

} // namespace cfg
} // namespace $GAME$
"""

# ─── GameEngine.h ─────────────────────────────────────────────────────

TPL_GAME_ENGINE_H = """\
#pragma once
// ============================================================
// GameEngine.h — Main engine class for $GAME$
// ============================================================
//
// Extends EngineBase to implement the full engine lifecycle:
//   1. EngineBase::run() calls initServices() (Config, AssetWatcher,
//      DLLLoader, DevServer — all automatic).
//   2. onInit() — you create the GLFW window, Vulkan device, render
//      graph, fill SystemContext, and load DLL plugins.
//   3. Main loop — EngineBase polls AssetWatcher + DevServer each frame,
//      then calls onFrame(dt) where you do game logic + rendering.
//   4. onShutdown() — save state, destroy GPU resources, close window.
//   5. EngineBase::shutdownServices() cleans up engine services.
//
// Entry point (at bottom of GameEngine.cpp):
//   int main(int argc, char** argv) {
//       GameEngine engine;
//       return engine.run(argc, argv);
//   }
//
// Generated by scaffold_game.py for $GAME$

#include "EngineBase.h"

namespace sv { struct SystemContext; }

class GameEngine : public sv::EngineBase {
public:
    GameEngine();
    ~GameEngine() override;

protected:
    bool onInit() override;
    void onShutdown() override;
    bool onFrame(float dt) override;

private:
    // TODO: Add your game-specific members.
    //
    // Typical members:
    //   GLFWwindow*        m_window  = nullptr;
    //   sv::VkCtx          m_vkCtx;           // Vulkan device + swapchain
    //   sv::RenderGraph    m_renderGraph;      // pass executor
    //   sv::SystemContext   m_ctx;             // DLL boundary context
    //   sv::SceneUBO        m_sceneUBO;        // per-frame GPU data
    //   bool                m_requestShutdown = false;
};
"""

# ─── GameEngine.cpp ───────────────────────────────────────────────────

TPL_GAME_ENGINE_CPP = """\
// ============================================================
// GameEngine.cpp — Engine init, shutdown, main loop + entry point
// ============================================================
//
// Generated by scaffold_game.py for $GAME$

#include "GameEngine.h"
#include "GameSystemContext.h"
#include "GameConfig.h"

// Engine service headers (available via EngineBase accessors)
#include "Config.h"
#include "AssetWatcher.h"
#include "DLLLoader.h"
#include "DevServer.h"
#include "EngineLog.h"
#include "SystemRegistry.h"

// ═══════════════════════════════════════════════════════════════
// Construction — configure engine paths BEFORE run()
// ═══════════════════════════════════════════════════════════════

GameEngine::GameEngine()
{
    setConfigPath("config.json");

    // Uncomment when you have a plugin DLL:
    // setPluginDLLPath("game_systems.dll");

    // DevServer port (default 9999, set 0 to disable):
    // setDevServerPort(9999);
}

GameEngine::~GameEngine() = default;

// ═══════════════════════════════════════════════════════════════
// onInit — called after engine services are ready
// ═══════════════════════════════════════════════════════════════
//
// At this point you have access to:
//   config()       — JSON config, auto-reloading
//   assetWatcher() — file change detection
//   dllLoader()    — DLL hot-reload
//   devServer()    — TCP debug commands
//   engineLog()    — ring-buffer log (also via SV_LOG_* macros)
//
// Your job:
//   1. Create GLFW window
//   2. Init Vulkan (instance, device, swapchain via VkCtx)
//   3. Build RenderGraph (register passes)
//   4. Fill SystemContext with Vulkan handles + function pointers
//   5. Load DLL plugins: dllLoader().load(m_ctx, plugins())
//   6. Wire DevServer bindings + register game commands
//
// Return false to abort startup.

bool GameEngine::onInit()
{
    // TODO: Implement your engine initialization.
    //
    // Example sketch:
    //
    //   // 1. Window
    //   int w = config().get<int>($GAME$::cfg::kWindowWidth, $GAME$::cfg::kDefaultWindowWidth);
    //   int h = config().get<int>($GAME$::cfg::kWindowHeight, $GAME$::cfg::kDefaultWindowHeight);
    //   m_window = glfwCreateWindow(w, h, "$GAME$", nullptr, nullptr);
    //
    //   // 2. Vulkan
    //   m_vkCtx.init(m_window);
    //
    //   // 3. RenderGraph
    //   m_renderGraph.init(m_vkCtx);
    //
    //   // 4. SystemContext (StratumV 1.2.0: fields grouped under sub-structs)
    //   //    See BaseSystemContext.h or docs/ENGINE_REF.md for the full API.
    //   m_ctx.device                           = m_vkCtx.device();
    //   m_ctx.allocator                        = m_vkCtx.allocator();
    //   m_ctx.ecs                              = &m_ecs;
    //   m_ctx.events                           = &m_events;
    //   m_ctx.windowWidth                      = w;
    //   m_ctx.windowHeight                     = h;
    //   m_ctx.rendering.hdrFormat              = VK_FORMAT_R16G16B16A16_SFLOAT;
    //   m_ctx.rendering.swapchainFormat        = m_vkCtx.swapchainFormat();
    //   m_ctx.rendering.renderWidth            = w;
    //   m_ctx.rendering.renderHeight           = h;
    //   m_ctx.input.isKeyDown                  = [this](int k){ return m_input.isKeyDown(k); };
    //   m_ctx.buffers.createBuffer             = [this](auto s,auto u,bool v){ return m_vkCtx.createBuffer(s,u,v); };
    //   m_ctx.vkfn.fnCmdBindPipeline           = vkCmdBindPipeline;
    //   m_ctx.audio.postAudioEvent             = [this](const char* n){ return m_audio.post(n); };
    //   m_ctx.animation.animationSystem        = &m_animationSystem;
    //   m_ctx.world.worldBounds                = &worldBounds();
    //   // ... (wire every BaseSystemContext field — see ENGINE_REF.md)
    //
    //   // 5. DLL plugins
    //   dllLoader().load(m_ctx, plugins());
    //
    //   // 6. DevServer
    //   devServer().registerCommand("get_state", ...);

    SV_LOG_INFO("Game", "$GAME$ initialized");
    return true;
}

// ═══════════════════════════════════════════════════════════════
// onShutdown — called after main loop exits
// ═══════════════════════════════════════════════════════════════
//
// Reverse of onInit.  DLL plugin shutdown is handled by EngineBase
// (via DLLLoader::shutdown), so you only need to clean up game-owned
// resources.

void GameEngine::onShutdown()
{
    // TODO: Reverse of onInit:
    //   1. Wait for GPU idle: vkDeviceWaitIdle(m_ctx.device)
    //   2. Save scene / config
    //   3. Destroy render graph
    //   4. Destroy Vulkan device
    //   5. Destroy GLFW window

    SV_LOG_INFO("Game", "$GAME$ shutting down");
}

// ═══════════════════════════════════════════════════════════════
// onFrame — called every frame by EngineBase::run()
// ═══════════════════════════════════════════════════════════════
//
// dt = seconds since last frame.
// Return false to exit the main loop.
//
// EngineBase already calls assetWatcher().checkAll() and
// devServer().pollCommands() before onFrame(), so you don't
// need to do that here.

bool GameEngine::onFrame(float dt)
{
    // TODO: Per-frame game logic:
    //
    //   glfwPollEvents();
    //   if (glfwWindowShouldClose(m_window)) return false;
    //
    //   // Input
    //   m_input.update(m_window);
    //
    //   // DLL hot-reload check (GPU must be idle first)
    //   // vkDeviceWaitIdle(m_ctx.device);
    //   // dllLoader().checkReload(m_ctx, plugins());
    //
    //   // Tick plugins
    //   for (auto* sys : plugins())
    //       sys->tick(dt, m_ctx);
    //
    //   // Render
    //   m_renderGraph.execute(m_ctx);
    //
    //   // Present
    //   m_vkCtx.present();

    return true;
}

// ═══════════════════════════════════════════════════════════════
// Entry point
// ═══════════════════════════════════════════════════════════════

int main(int argc, char** argv) {
    GameEngine engine;
    return engine.run(argc, argv);
}
"""

# ─── ExamplePlugin.h ─────────────────────────────────────────────────

TPL_EXAMPLE_PLUGIN_H = """\
#pragma once
// ============================================================
// ExamplePlugin.h — Minimal StratumV DLL plugin for $GAME$
// ============================================================
//
// This is a complete, working IModularSystem implementation.
// Rename it, modify it, use it as a starting point for your
// game systems.
//
// IModularSystem lifecycle:
//   1. DLLLoader loads the .dll, calls createSystems()
//   2. Engine checks getInterfaceVersion() — rejects mismatches
//   3. Systems sorted by initPriority() (lower = earlier)
//   4. init() called on each system (return false = block start)
//   5. postInit() called on each (wire up fn ptrs in SystemContext)
//   6. Main loop: tick() -> record*() -> drawUI() each frame
//   7. Hot-reload: serializeState() -> unload -> reload ->
//      init() -> deserializeState() -> onReload()
//   8. Shutdown: shutdown() -> destroySystems() -> FreeLibrary
//
// Generated by scaffold_game.py for $GAME$

#include "IModularSystem.h"

#include <string>
#include <functional>

namespace sv {

class ExamplePlugin : public IModularSystem {
public:
    // ── Identity ──────────────────────────────────────────────
    //
    // name() must return a unique, stable string. It's used as:
    //   - Registry key in SystemRegistry
    //   - Serialization key for scene state persistence
    //   - Display name in admin panel and DevServer health reports
    //
    // Don't change it after shipping — serialized scenes reference it.

    const char* name() const override { return "ExamplePlugin"; }

    // ── Connectome Metadata ───────────────────────────────────
    //
    // getMeta() provides self-description for the system graph.
    // Fields: id, label, emoji, layer, color, description,
    //         capabilities, sourceFiles, notes, progress, session,
    //         dependency.
    // Optional but recommended. Default uses name() as a stub.

    NodeMeta getMeta() const override {
        return {
            "example",                                     // id
            "Example Plugin",                              // label
            "",                                            // emoji
            8,                                             // layer
            "#4a9eff",                                     // color
            "A minimal example plugin for $GAME$",         // description
            "",                                            // capabilities
            "src/plugins/example_plugin/ExamplePlugin.h,"
            "src/plugins/example_plugin/ExamplePlugin.cpp",// sourceFiles
            "",                                            // notes
            0.0f,                                          // progress
            "",                                            // session
            ""                                             // dependency
        };
    }

    // ── Health Reporting ──────────────────────────────────────
    //
    // Returns 0-100 score + boolean flag.
    // DevServer get_health returns this for all systems.

    HealthReport getHealth() const override {
        return { m_initialized ? 100.0f : 0.0f, m_initialized };
    }

    // ── Lifecycle (REQUIRED — pure virtual) ───────────────────

    bool init(const SystemContext& ctx) override;
    void shutdown() override;

    // ── Lifecycle (optional) ──────────────────────────────────

    void postInit(SystemContext& ctx) override;
    void tick(float dt, const SystemContext& ctx) override;

    // ── Rendering Hooks (optional) ────────────────────────────
    //
    // Uncomment the hooks you need. See IModularSystem.h for all.
    // hookMode() controls which hooks the engine calls:
    //   PreDraw  = recordPreDraw only  (before terrain/ocean)
    //   PostDraw = recordPostDraw only (after terrain/ocean) [default]
    //   Both     = both hooks called

    // void recordPreDraw(VkCommandBuffer cmd, const FrameData& frame,
    //                     const SystemContext& ctx) override;
    // void recordPostDraw(VkCommandBuffer cmd, const FrameData& frame,
    //                      const SystemContext& ctx) override;

    HookMode hookMode() const override { return PostDraw; }

    // ── Admin UI (optional) ───────────────────────────────────
    //
    // drawUI() is called inside the ImGui admin panel.
    // adminTab() groups this system's UI into a named tab.
    // Return nullptr for standalone (not in any tab).

    void drawUI() override;
    const char* adminTab() const override { return "Game"; }

    // ── Init Priority (optional) ──────────────────────────────
    //
    // Lower values initialize first. Default is 0.
    // Use if your plugin depends on another plugin's postInit output.
    // Example: TerrainSystem(0) -> FoliageSystem(10) -> TreeSystem(20)

    int32_t initPriority() const override { return 0; }

    // ── Serialization (optional) ──────────────────────────────
    //
    // serializeState/deserializeState preserve state across hot-reload.
    // Return a JSON string. Engine stores it, passes it back after
    // the DLL is reloaded.

    std::string serializeState() override;
    void deserializeState(const std::string& json) override;

    // ── Hot-Reload (optional) ─────────────────────────────────

    void onReload(const SystemContext& ctx) override;
    void onResourcesInvalidated(const SystemContext& ctx) override;

private:
    bool  m_initialized = false;
    float m_timer       = 0.0f;

    // Store references needed for shutdown (shutdown() has no ctx param).
    // Example: VkDevice m_device = VK_NULL_HANDLE;
    // Example: std::function<void(VkBuf&)> m_destroyBuffer;
};

} // namespace sv
"""

# ─── ExamplePlugin.cpp ───────────────────────────────────────────────

TPL_EXAMPLE_PLUGIN_CPP = """\
// ============================================================
// ExamplePlugin.cpp — Implementation + DLL exports
// ============================================================
//
// Generated by scaffold_game.py for $GAME$

#include "ExamplePlugin.h"
#include "GameSystemContext.h"  // sv::SystemContext (extends BaseSystemContext)

#include <imgui.h>
#include <nlohmann/json.hpp>    // bundled with StratumV

namespace sv {

// ── init ──────────────────────────────────────────────────────
//
// Called once when the plugin is loaded. Store references to
// anything you'll need later (especially for shutdown).
//
// Return false to signal a fatal error — engine will not start.
//
// IMPORTANT: Don't read other plugins' function pointers here.
// They may not be set yet (depends on init order). Use postInit()
// for that.

bool ExamplePlugin::init(const SystemContext& ctx) {
    // Store references needed for shutdown (which has no ctx param):
    //   m_device = ctx.device;
    //   m_destroyBuffer = ctx.buffers.destroyBuffer;

    // TODO: Initialize your system.
    //
    // Example — create a GPU buffer:
    //   if (ctx.buffers.createBuffer) {
    //       m_buffer = ctx.buffers.createBuffer(sizeof(MyData),
    //           VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT, true);
    //   }
    //
    // Example — access ECS:
    //   auto view = ctx.ecs->view<TransformComponent>();

    m_initialized = true;
    return true;
}

// ── postInit ──────────────────────────────────────────────────
//
// Called AFTER all plugins have init()'d. Safe to read other
// plugins' fn ptrs. Publish your own services here.
//
// Example: if this plugin provides terrain height queries:
//   ctx.getTerrainHeight = [this](float x, float z) {
//       return sampleHeight(x, z);
//   };

void ExamplePlugin::postInit(SystemContext& ctx) {
    // TODO: Publish any services to SystemContext.
}

// ── shutdown ──────────────────────────────────────────────────
//
// ================================================================
// | CRITICAL: Release ALL Vulkan resources here.                 |
// |                                                              |
// | After shutdown() returns, the engine calls FreeLibrary on    |
// | your DLL. Any Vulkan handles you created (buffers, images,   |
// | pipelines, descriptor pools/sets/layouts, samplers, image    |
// | views, shader modules) MUST be destroyed before that.        |
// |                                                              |
// | Leaked handles = Vulkan validation errors at best,           |
// | device lost / crash at worst.                                |
// ================================================================
//
// NOTE: shutdown() has no SystemContext parameter. Store any
// destroy functions or device handles during init().

void ExamplePlugin::shutdown() {
    // TODO: Release GPU resources using stored references.
    //
    // Example:
    //   if (m_buffer.buffer != VK_NULL_HANDLE && m_destroyBuffer) {
    //       m_destroyBuffer(m_buffer);   // stored from ctx.buffers.destroyBuffer in init()
    //   }
    //   if (m_pipeline != VK_NULL_HANDLE) {
    //       vkDestroyPipeline(m_device, m_pipeline, nullptr);
    //       m_pipeline = VK_NULL_HANDLE;
    //   }

    m_initialized = false;
}

// ── tick ──────────────────────────────────────────────────────
//
// Called every frame. dt = seconds since last frame.
// Use for game logic, ECS updates, audio events.
// Do NOT record Vulkan commands here — use record*() hooks.

void ExamplePlugin::tick(float dt, const SystemContext& ctx) {
    m_timer += dt;

    // TODO: Per-frame logic.
    //
    // Example — read scene state:
    //   if (ctx.sceneState) {
    //       float sunY = ctx.sceneState->sunDirection.y;
    //   }
    //
    // Example — check input (note: input fn-ptrs live under ctx.input):
    //   if (ctx.input.isKeyPressed && ctx.input.isKeyPressed(GLFW_KEY_F)) {
    //       doSomething();
    //   }
}

// ── drawUI ────────────────────────────────────────────────────
//
// Called inside the ImGui admin panel, under adminTab() tab.
// ImGui context is already set.

void ExamplePlugin::drawUI() {
    ImGui::Text("Example Plugin");
    ImGui::Separator();
    ImGui::Text("Timer: %.2f s", m_timer);
    ImGui::Text("Status: %s", m_initialized ? "Running" : "Stopped");

    // TODO: Add your debug UI.
    //
    // Example — slider:
    //   static float myValue = 1.0f;
    //   ImGui::SliderFloat("My Value", &myValue, 0.0f, 10.0f);
}

// ── serializeState ────────────────────────────────────────────
//
// Returns a JSON string representing this plugin's hot-reload state.
// Called before DLL unload and during scene save.
// Keep it small — stored in memory during reload.

std::string ExamplePlugin::serializeState() {
    nlohmann::json j;
    j["timer"] = m_timer;
    // TODO: Add fields to preserve across hot-reload.
    return j.dump();
}

// ── deserializeState ──────────────────────────────────────────
//
// Restore state from the JSON that serializeState() produced.

void ExamplePlugin::deserializeState(const std::string& json) {
    try {
        auto j = nlohmann::json::parse(json);
        m_timer = j.value("timer", 0.0f);
        // TODO: Restore your fields.
    } catch (...) {
        // Gracefully handle corrupt/missing data after format changes.
    }
}

// ── onReload ──────────────────────────────────────────────────
//
// Called after hot-reload (DLL reloaded, state restored).
// Re-acquire pointers or references that may have changed.
// ECS components survive reload — re-query views here.

void ExamplePlugin::onReload(const SystemContext& ctx) {
    // TODO: Re-acquire references if you cached anything.
}

// ── onResourcesInvalidated ────────────────────────────────────
//
// Called when engine GPU resources are recreated (resolution change,
// DLSS mode switch). Rebind descriptor sets that reference engine-
// owned textures (depth, color, HZB).

void ExamplePlugin::onResourcesInvalidated(const SystemContext& ctx) {
    // TODO: Rebind descriptors referencing engine resources.
}

} // namespace sv

// ═══════════════════════════════════════════════════════════════
//  DLL Export Interface
// ═══════════════════════════════════════════════════════════════
//
// DLLLoader calls these to create and destroy plugin instances.
// A single DLL can export multiple systems — increase the array
// size and count accordingly.
//
// createSystems:  allocate instances, return pointer array + count.
// destroySystems: deallocate everything createSystems allocated.

#if defined(_WIN32)
  #define PLUGIN_EXPORT extern "C" __declspec(dllexport)
#else
  #define PLUGIN_EXPORT extern "C" __attribute__((visibility("default")))
#endif

static sv::ExamplePlugin* s_instance = nullptr;
static sv::IModularSystem* s_systems[1] = {};

PLUGIN_EXPORT sv::IModularSystem** createSystems(int* outCount) {
    s_instance = new sv::ExamplePlugin();
    s_systems[0] = s_instance;
    *outCount = 1;
    return s_systems;
}

PLUGIN_EXPORT void destroySystems() {
    delete s_instance;
    s_instance = nullptr;
}
"""

# ─── Plugin CMakeLists.txt ────────────────────────────────────────────

TPL_PLUGIN_CMAKE = """\
# ============================================================
# example_plugin — Minimal StratumV DLL plugin for $GAME$
# ============================================================
#
# Builds a .dll that DLLLoader discovers and hot-reloads at runtime.
# Place the output .dll in the engine's plugin scan directory.

add_library(example_plugin SHARED
    ExamplePlugin.h
    ExamplePlugin.cpp
)

target_link_libraries(example_plugin PRIVATE stratumv)

# Game headers (SceneUBO.h, GameSystemContext.h) needed by plugins
target_include_directories(example_plugin PRIVATE
    ${CMAKE_SOURCE_DIR}/src/game
)

# Output DLL next to the game executable
set_target_properties(example_plugin PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/$<CONFIG>/plugins"
)
"""

# ─── Top-level CMakeLists.txt ─────────────────────────────────────────

TPL_TOP_CMAKE = """\
# ============================================================
# $GAME$ — StratumV game project
# ============================================================
#
# Build:
#   cmake -B build -G "Visual Studio 17 2022" -A x64
#   cmake --build build --config Release --parallel
#
# Prerequisites:
#   - StratumV repo at ../StratumV (or adjust the path below)
#   - Same compiler/toolchain as StratumV (VS 2022, C++20)

cmake_minimum_required(VERSION 3.24)
project($GAME$ VERSION 0.1.0 LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(FetchContent)

# ── StratumV engine ────────────────────────────────────────────
# Adjust the path if your StratumV checkout is elsewhere.
add_subdirectory(../StratumV ${CMAKE_BINARY_DIR}/stratumv)

# ── ImGui sources ──────────────────────────────────────────────
# stratumv.lib provides ImGui HEADERS but not compiled objects.
# Each game must compile ImGui sources into its own executable.
FetchContent_GetProperties(imgui)

# ── Game executable ────────────────────────────────────────────
# GameEngine.cpp contains main() and extends EngineBase.
# See GameEngine.h for the lifecycle documentation.

add_executable(${PROJECT_NAME}
    src/game/GameEngine.h
    src/game/GameEngine.cpp

    # ImGui sources (required — stratumv.lib links against these symbols)
    ${imgui_SOURCE_DIR}/imgui.cpp
    ${imgui_SOURCE_DIR}/imgui_draw.cpp
    ${imgui_SOURCE_DIR}/imgui_tables.cpp
    ${imgui_SOURCE_DIR}/imgui_widgets.cpp
    ${imgui_SOURCE_DIR}/backends/imgui_impl_glfw.cpp
    ${imgui_SOURCE_DIR}/backends/imgui_impl_vulkan.cpp
)

target_link_libraries(${PROJECT_NAME} PRIVATE stratumv)
target_include_directories(${PROJECT_NAME} PRIVATE src/game)

target_compile_definitions(${PROJECT_NAME} PRIVATE
    VK_USE_PLATFORM_WIN32_KHR
    VK_NO_PROTOTYPES
)

# ── DLL plugins ────────────────────────────────────────────────
# Each plugin is a SHARED library loaded at runtime by DLLLoader.
add_subdirectory(src/plugins/example_plugin)
"""

# ─── GAME_CONTRACT.md ─────────────────────────────────────────────────

TPL_GAME_CONTRACT = """\
# $GAME$ — Game Contract

Hard rules for developing $GAME$ on StratumV. Violating these produces
crashes, Vulkan validation errors, or subtle hot-reload bugs that are
difficult to diagnose.

---

## 1. Namespace Rule

`SystemContext` **must** be defined in `namespace sv`.

IModularSystem.h forward-declares `sv::SystemContext`. If your definition
is in a different namespace, the compiler cannot find it. Your
GameSystemContext.h must contain:

```cpp
namespace sv {
struct SystemContext : BaseSystemContext { /* ... */ };
}
```

---

## 2. Plugin Lifecycle Contract

### Init Order

1. DLLLoader discovers `.dll` files in the plugin scan directory
2. `createSystems()` called on each DLL (instances allocated)
3. `getInterfaceVersion()` checked — mismatched plugins are rejected
4. Plugins sorted by `initPriority()` (ascending: 0, 10, 20, ...)
5. `init(ctx)` called on each plugin in priority order
6. `postInit(ctx)` called on each plugin (same order)
7. Main loop begins

### Shutdown Order

1. `shutdown()` called on each plugin (reverse init order)
2. `destroySystems()` called (instances deallocated)
3. `FreeLibrary()` unloads the DLL

### postInit() vs init()

- In `init()`: engine fields in SystemContext are populated, but other
  plugins' function pointers may not be set yet.
- In `postInit()`: all plugins have init()'d. Safe to read other plugins'
  function pointers. Safe to publish your own.

---

## 3. GPU Resource Ownership

**Every Vulkan handle you create, you must destroy in shutdown().**

This includes: VkBuffer, VkImage, VkImageView, VkSampler, VkPipeline,
VkPipelineLayout, VkDescriptorPool, VkDescriptorSetLayout, VkShaderModule,
and any VMA allocations.

After `shutdown()` returns, the engine calls `FreeLibrary`. Leaked handles
cause Vulkan validation errors or device loss.

`shutdown()` has no SystemContext parameter. Store device handles and
destroy functions during `init()`:

```cpp
// In init():
m_device = ctx.device;
m_destroyBuffer = ctx.destroyBuffer;

// In shutdown():
if (m_buffer.buffer != VK_NULL_HANDLE && m_destroyBuffer)
    m_destroyBuffer(m_buffer);
```

---

## 4. ECS Components and Hot-Reload

During hot-reload, the engine:

1. Calls `serializeState()` on your plugin
2. Calls `shutdown()` on your plugin
3. Calls `destroySystems()` — your instance is deleted
4. Unloads the old DLL
5. Loads the new DLL
6. Calls `createSystems()` — new instance created
7. Calls `init()` — re-initialize with SystemContext
8. Calls `deserializeState()` — restore your state
9. Calls `onReload()` — re-acquire references

**ECS components survive hot-reload.** The EnTT registry is engine-owned,
not DLL-owned. After reload:

- Re-query `ctx.ecs->view<YourComponent>()` — don't cache iterators
- Component data is intact — `deserializeState()` can skip ECS state
- If your component type has vtables or function pointers into DLL
  memory, they are invalid after reload. Use POD components.

---

## 5. DLL Boundary Rules

**Do not pass across the DLL boundary:**
- `std::string` (ABI may differ if DLLs built separately)
- `std::vector`, `std::map`, `std::unordered_map`
- Any STL container with allocators

**Safe to pass:**
- `const char*` (null-terminated C string)
- Pointers to POD structs
- `std::function<>` (safe when both sides share the same CRT — StratumV
  ensures this by building everything with the same VS 2022 toolchain)
- Vulkan handles (opaque 64-bit, ABI-safe)

Note: if you ever use a different compiler for plugins, restrict
cross-boundary types to C-compatible only.

---

## 6. Null-Check Function Pointers

Always check SystemContext function pointers before calling. Note that
input/buffer/audio/etc. function pointers live under nested sub-structs
(StratumV 1.2.0):

```cpp
if (ctx.input.isKeyPressed && ctx.input.isKeyPressed(GLFW_KEY_F)) { /* ... */ }
if (ctx.buffers.createBuffer) auto b = ctx.buffers.createBuffer(...);
if (ctx.audio.postAudioEvent) ctx.audio.postAudioEvent("door_open");
```

A function pointer may be null if:
- The providing system is not loaded
- The engine was built without that feature (e.g. audio disabled)
- You're calling during init() and the provider hasn't postInit()'d yet

DLLLoader sweeps for null function pointers and logs warnings,
but does not prevent your plugin from running.

---

## 7. Thread Safety

- `init()`, `postInit()`, `tick()`, `shutdown()`, all `record*()` hooks,
  and `drawUI()` are called from the **main thread**
- Do not spawn threads that access SystemContext or ECS
- If you need async work (file I/O, network), use your own thread with
  your own data, and sync results back in `tick()`

---

## 8. Build Requirements

- **C++20** — same standard as StratumV
- **Link against `stratumv`** — static library provides all engine headers
- **Include game headers** — SceneUBO.h, GameSystemContext.h
- **Same compiler + CRT** — VS 2022 recommended (must match StratumV)
- **Output: SHARED library** (.dll) placed in the plugin scan directory
"""

# ─── DEVSERVER_API.md ─────────────────────────────────────────────────

TPL_DEVSERVER_API = """\
# StratumV DevServer — Command Reference

TCP debug server on `localhost:9999`. Accepts JSON commands, returns JSON
responses. Engine commands are built-in; games extend with
`registerCommand()` / `registerMainThreadCommand()`.

---

## Protocol

1. Connect via TCP to `127.0.0.1:9999`
2. Server sends welcome: `{"welcome":"StratumV DevServer v1.0"}\\n`
3. Client sends one JSON command followed by `\\n`
4. Server responds with one JSON response followed by `\\n`
5. Connection closes

One command per connection. For multiple commands, use `batch` or open
multiple connections. Maximum request size: 4096 bytes.

### Example (Python)

```python
import socket, json

def dev_cmd(cmd, port=9999):
    with socket.create_connection(("127.0.0.1", port)) as s:
        s.recv(256)  # read welcome
        s.sendall((json.dumps(cmd) + "\\n").encode())
        return json.loads(s.recv(65536))

result = dev_cmd({"cmd": "status"})
print(result["fps"])
```

### Authentication

Introspection commands (`get_graph`, `get_health`) require a token when
the `STRATUMV_ADMIN_TOKEN` environment variable is set:

```json
{"cmd": "get_health", "auth": "your-token-here"}
```

Other commands do not require authentication.

---

## Read-Only Commands

Run on the TCP server thread. Read a snapshot of engine state.

### status

Basic frame statistics.

| Field   | Type   | Description               |
|---------|--------|---------------------------|
| fps     | float  | Frames per second         |
| dt      | float  | Delta time (seconds)      |
| time    | float  | Time since start          |
| width   | int    | Window width              |
| height  | int    | Window height             |
| gpu     | string | GPU device name           |

```
-> {"cmd": "status"}
<- {"ok": true, "fps": 60.0, "dt": 0.0166, "time": 123.4,
    "width": 1920, "height": 1080, "gpu": "NVIDIA GeForce RTX 4090"}
```

### get_state

Detailed state query with selectable targets.

| Target         | Returns                                         |
|----------------|-------------------------------------------------|
| `"frame"`      | fps, dt, time, adminOpen                        |
| `"timing"`     | GPU pass timings (needs gpuProfilingEnabled)    |
| `"vram"`       | VRAM used/budget/percentage                     |
| `"render"`     | DLSS, ReSTIR, SHaRC settings                   |
| `"postprocess"`| bloom, exposure, gamma                          |
| `"all"`        | All of the above (default)                      |

```
-> {"cmd": "get_state", "target": "render"}
<- {"ok": true, "render": {"dlssEnabled": true, "restirEnabled": true,
    "sharcEnabled": false, "dlssQualityIndex": 1, "rtShadowManual": false,
    "sharcLogBase": 2.0, "sharcLevelBias": 0.0, "sharcStaleFrameMax": 128}}
```

Games extend `get_state` with additional targets via `registerCommand("get_state", ...)`.

### get_graph

Connectome system graph (auth-guarded).

```
-> {"cmd": "get_graph", "auth": "token"}
<- {"ok": true, "graph": {...}}
```

### get_health

Health reports for all registered systems (auth-guarded).

```
-> {"cmd": "get_health", "auth": "token"}
<- {"ok": true, "health": {...}}
```

### screenshot / screenshot_depth / screenshot_normals

Capture a frame buffer to a PNG file.

```
-> {"cmd": "screenshot", "path": "captures/color.png"}
<- {"ok": true, "path": "captures/color.png", "size": [1920, 1080]}

-> {"cmd": "screenshot_depth", "path": "captures/depth.png"}
<- {"ok": true, "path": "captures/depth.png", "size": [1920, 1080]}

-> {"cmd": "screenshot_normals", "path": "captures/normals.png"}
<- {"ok": true, "path": "captures/normals.png", "size": [1920, 1080]}
```

### observe

Screenshot + status combined in one request.

```
-> {"cmd": "observe", "path": "captures/frame.png"}
<- {"ok": true, "path": "captures/frame.png", "size": [1920, 1080],
    "fps": 60.0, "dt": 0.0166, "time": 123.4,
    "width": 1920, "height": 1080, "gpu": "..."}
```

### reload

Request shader hot-reload on next frame.

```
-> {"cmd": "reload"}
<- {"ok": true, "reload": "requested"}
```

### batch

Execute multiple commands in one connection.

```
-> {"cmd": "batch", "commands": [
     {"cmd": "status"},
     {"cmd": "get_state", "target": "render"}
   ]}
<- {"ok": true, "results": [{...}, {...}]}
```

---

## Write Commands

Queued to the main thread, executed on the next frame. Timeout: 5 seconds.

### Input Injection

```
-> {"cmd": "inject_key", "key": "W"}
<- {"ok": true, "key": "W"}

-> {"cmd": "inject_key_hold", "key": "W", "duration_ms": 1000}
<- {"ok": true, "key": "W", "duration_ms": 1000}

-> {"cmd": "inject_key_release", "key": "W"}
<- {"ok": true, "key": "W"}

-> {"cmd": "inject_mouse", "dx": 10.0, "dy": -5.0}
<- {"ok": true, "dx": 10.0, "dy": -5.0}

-> {"cmd": "inject_scroll", "delta": 1.0}
<- {"ok": true, "delta": 1.0}

-> {"cmd": "inject_click", "x": 960.0, "y": 540.0, "button": 0}
<- {"ok": true, "x": 960.0, "y": 540.0, "button": 0}
```

Key names use GLFW conventions: `W`, `A`, `Space`, `Escape`, `LeftShift`,
`F1`, `Enter`, etc.

### toggle_feature

Toggle a render feature on/off.

```
-> {"cmd": "toggle_feature", "feature": "dlss"}
<- {"ok": true, "feature": "dlss", "enabled": false}
```

Valid features: `dlss`, `restir`, `sharc`.

### set_admin

Open or close the admin panel.

```
-> {"cmd": "set_admin", "open": true}
<- {"ok": true, "adminOpen": true}
```

### set_state

Modify engine state values.

**Post-process fields:** `bloomThreshold`, `bloomIntensity`, `exposure`, `gamma`

```
-> {"cmd": "set_state", "target": "postprocess", "field": "exposure", "value": 1.5}
<- {"ok": true, "target": "postprocess", "field": "exposure"}
```

**Render fields:** `dlssQualityIndex`, `rtShadowManual`, `sharcLogBase`,
`sharcLevelBias`, `sharcStaleFrameMax`, `gpuProfilingEnabled`

```
-> {"cmd": "set_state", "target": "render", "field": "dlssQualityIndex", "value": 2}
<- {"ok": true, "target": "render", "field": "dlssQualityIndex"}
```

Games extend `set_state` with additional targets via
`registerMainThreadCommand("set_state", ...)`.

### Scene Persistence

```
-> {"cmd": "save_scene"}
<- {"ok": true}

-> {"cmd": "load_scene"}
<- {"ok": true}

-> {"cmd": "reset_scene"}
<- {"ok": true}
```

---

## Extending the DevServer

Register custom commands in your game initialization:

```cpp
// Server-thread handler (read-only — runs on TCP thread)
devServer.registerCommand("get_weather", [&](const nlohmann::json& cmd) {
    return nlohmann::json{{"ok", true}, {"temp", weather.temp}};
});

// Main-thread handler (can write state — runs on game loop)
devServer.registerMainThreadCommand("set_weather",
    [&](const nlohmann::json& cmd) {
    weather.temp = cmd.value("temperature", 20.0f);
    return nlohmann::json{{"ok", true}};
});
```

### Extending get_state / set_state

Add game-specific targets without new command names:

```cpp
// Read-only extension (server thread)
devServer.registerCommand("get_state", [&](const nlohmann::json& cmd) {
    std::string target = cmd.value("target", "");
    nlohmann::json resp;
    if (target == "weather" || target == "all")
        resp["weather"] = {{"temp", weather.temp}};
    return resp;  // merged with engine's response
});

// Writable extension (main thread)
devServer.registerMainThreadCommand("set_state",
    [&](const nlohmann::json& cmd) {
    std::string target = cmd.value("target", "");
    if (target == "weather") {
        weather.temp = cmd["value"].get<float>();
        return nlohmann::json{{"ok", true}};
    }
    return nlohmann::json{{"ok", false}, {"error", "unknown target"}};
});
```

---

## Error Responses

All commands return `{"ok": false, "error": "..."}` on failure:

| Error                                        | Cause                          |
|----------------------------------------------|--------------------------------|
| `"unknown command: X"`                       | Unrecognized command name      |
| `"unknown key: X"`                           | Invalid GLFW key name          |
| `"unknown feature: X"`                       | Invalid toggle_feature target  |
| `"screenshot failed or timed out"`           | GPU capture failed or >5s      |
| `"unauthorized"`                             | Missing/wrong auth token       |
| `"command timed out waiting for main thread"`| Main thread didn't respond     |
| `"batch requires 'commands' array"`          | Malformed batch request        |
| `"invalid JSON"`                             | Request parse failure          |

---

*Generated by scaffold_game.py for $GAME$*
"""


# ═══════════════════════════════════════════════════════════════════════
#  Helpers
# ═══════════════════════════════════════════════════════════════════════

def expand(template: str, game: str) -> str:
    """Replace $GAME$ placeholder in a template string."""
    return template.replace("$GAME$", game)


def write_file(path: Path, content: str) -> None:
    """Write content to path, creating parent dirs as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


# ═══════════════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a new StratumV game project")
    parser.add_argument("game",
        help="Game name (valid C++ identifier, e.g. MyGame)")
    parser.add_argument("-o", "--output",
        help="Output directory (default: ../<game> relative to StratumV)")
    parser.add_argument("--force", action="store_true",
        help="Overwrite files in an existing output directory")
    args = parser.parse_args()

    game = args.game
    if not game.isidentifier():
        print(f"ERROR: '{game}' is not a valid C++ identifier",
              file=sys.stderr)
        sys.exit(1)

    out = Path(args.output) if args.output else REPO_ROOT.parent / game
    out = out.resolve()

    if out.exists():
        if not out.is_dir():
            print(f"ERROR: path exists and is not a directory: {out}",
                  file=sys.stderr)
            sys.exit(1)
        if any(out.iterdir()) and not args.force:
            print(f"ERROR: directory not empty: {out}", file=sys.stderr)
            print("  Use --force to overwrite", file=sys.stderr)
            sys.exit(1)

    files = [
        (out / "CMakeLists.txt",                             TPL_TOP_CMAKE),
        (out / "GAME_CONTRACT.md",                           TPL_GAME_CONTRACT),
        (out / "DEVSERVER_API.md",                           TPL_DEVSERVER_API),
        (out / "src" / "game" / "SceneUBO.h",                TPL_SCENE_UBO),
        (out / "src" / "game" / "GameSystemContext.h",        TPL_GAME_SYSTEM_CONTEXT),
        (out / "src" / "game" / "GameConfig.h",               TPL_GAME_CONFIG),
        (out / "src" / "game" / "GameEngine.h",              TPL_GAME_ENGINE_H),
        (out / "src" / "game" / "GameEngine.cpp",            TPL_GAME_ENGINE_CPP),
        (out / "src" / "plugins" / "example_plugin" / "CMakeLists.txt",
                                                              TPL_PLUGIN_CMAKE),
        (out / "src" / "plugins" / "example_plugin" / "ExamplePlugin.h",
                                                              TPL_EXAMPLE_PLUGIN_H),
        (out / "src" / "plugins" / "example_plugin" / "ExamplePlugin.cpp",
                                                              TPL_EXAMPLE_PLUGIN_CPP),
    ]

    for path, template in files:
        write_file(path, expand(template, game))
        print(f"  wrote {path.relative_to(out)}")

    print(f"\nScaffolded {game} -> {out}  ({len(files)} files)")
    print(f"\nNext steps:")
    print(f"  1. Implement GameEngine::onInit() — window, Vulkan, context wiring")
    print(f"  2. Review and customize src/game/SceneUBO.h")
    print(f"  3. Add game-specific fields to src/game/GameSystemContext.h")
    print(f"  4. Rename/modify src/plugins/example_plugin/")
    print(f"  5. Read GAME_CONTRACT.md before writing your first plugin")


if __name__ == "__main__":
    main()
